name:                swisstable
version:             0.1.0.1
github:              "nakaji-dayo/swisstable"
license:             BSD3
author:              "Daishi Nakajima"
maintainer:          "nakaji.dayo@gmail.com"
copyright:           "2021 Daishi Nakajima"

extra-source-files:
- README.md
- ChangeLog.md
- csrc/simd.c

# Metadata used when publishing your package
synopsis:            Google's SwissTable hash map
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nakaji-dayo/swisstable#readme>

dependencies:
- base >= 4.7 && < 5
- wide-word
- hashable
- vector
- primitive
- deepseq

library:
  source-dirs: src
  c-sources:
    - csrc/simd.c
  ghc-options:
    - -O2
    - -Wall
  cc-options:
    - -mavx2

tests:
  swisstable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - swisstable
    - tasty-discover
    - tasty
    - tasty-hunit
    - QuickCheck
    build-tool-depends:
    - hspec-discover:hspec-discover

executables:
  swisstable-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    # - -threaded
    # - -rtsopts
    # - -with-rtsopts=-N
    - -O2
    dependencies:
    - swisstable
    - criterion
    - hashtables
    - QuickCheck
