name: Hackage release

on:
  push:
    branches: [ test-release ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        cabal update
        cabal install tasty-discover
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build
    - name: sdist
      run: cabal sdist
    - name: upload
      run: |
        echo ${HACKAGE_USERNAME}
        cabal upload --username=${HACKAGE_USERNAME} --password=${HACKAGE_PASSWORD} dist-newstyle/sdist/*
